DROP TABLE IF EXISTS files;
CREATE TABLE files (
	   id INTEGER PRIMARY KEY,
	   name TEXT UNIQUE NOT NULL,
	   description TEXT NOT NULL,
	   createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	   modifiedAt TIMESTAMP
)
